name: Test and Deployment CI-CD

on:
  push:
    branches:
      - main
      - staging
      - deploy

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push message consumer image
      run: |
        docker build -t ${{ secrets.DOCKER_IMAGE_MESSAGE_CONSUMER }} .
        docker push ${{ secrets.DOCKER_IMAGE_MESSAGE_CONSUMER }}
